# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PICG' do
    pod 'BMSCore', '~> 2.0'

  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PICG

  target 'PICGTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PICGUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
